// <auto-generated />
using System;
using Kolokwium.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kolokwium.Migrations
{
    [DbContext(typeof(FireDbContext))]
    [Migration("20200621100307_KOLOS")]
    partial class KOLOS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kolokwium.Models.Action", b =>
                {
                    b.Property<int>("IdAction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("NeedSpecialEquipment")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAction");

                    b.ToTable("Action");

                    b.HasData(
                        new
                        {
                            IdAction = 1,
                            EndTime = new DateTime(2020, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            NeedSpecialEquipment = (byte)1,
                            StartTime = new DateTime(2020, 6, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdAction = 2,
                            EndTime = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            NeedSpecialEquipment = (byte)2,
                            StartTime = new DateTime(2020, 6, 24, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            IdAction = 3,
                            EndTime = new DateTime(2020, 6, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            NeedSpecialEquipment = (byte)3,
                            StartTime = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.FireTruck", b =>
                {
                    b.Property<int>("IdFireTruck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OperationalNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<byte>("SpecialEquipment")
                        .HasColumnType("tinyint");

                    b.HasKey("IdFireTruck");

                    b.ToTable("FireTruck");

                    b.HasData(
                        new
                        {
                            IdFireTruck = 1,
                            OperationalNumber = "Pozarowy",
                            SpecialEquipment = (byte)3
                        },
                        new
                        {
                            IdFireTruck = 2,
                            OperationalNumber = "Latajacy",
                            SpecialEquipment = (byte)2
                        },
                        new
                        {
                            IdFireTruck = 3,
                            OperationalNumber = "Wodny",
                            SpecialEquipment = (byte)1
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.FireTruck_Action", b =>
                {
                    b.Property<int>("IdFireTruck_Action")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AssigmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.Property<int>("IdFireTruck")
                        .HasColumnType("int");

                    b.HasKey("IdFireTruck_Action");

                    b.HasIndex("IdAction");

                    b.HasIndex("IdFireTruck");

                    b.ToTable("FireTruck_Action");

                    b.HasData(
                        new
                        {
                            IdFireTruck_Action = 1,
                            AssigmentDate = new DateTime(2020, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IdAction = 1,
                            IdFireTruck = 3
                        },
                        new
                        {
                            IdFireTruck_Action = 2,
                            AssigmentDate = new DateTime(2020, 6, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            IdAction = 2,
                            IdFireTruck = 2
                        },
                        new
                        {
                            IdFireTruck_Action = 3,
                            AssigmentDate = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            IdAction = 3,
                            IdFireTruck = 1
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Firefighter", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdFirefighter");

                    b.ToTable("Firefighter");

                    b.HasData(
                        new
                        {
                            IdFirefighter = 1,
                            Firstname = "Rafał",
                            LastName = "Smoczynski"
                        },
                        new
                        {
                            IdFirefighter = 2,
                            Firstname = "Kasia",
                            LastName = "Smoczynska"
                        },
                        new
                        {
                            IdFirefighter = 3,
                            Firstname = "Maria",
                            LastName = "Ligowska"
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.Firefighter_Action", b =>
                {
                    b.Property<int>("IdFirefighter")
                        .HasColumnType("int");

                    b.Property<int>("IdAction")
                        .HasColumnType("int");

                    b.HasKey("IdFirefighter", "IdAction");

                    b.HasIndex("IdAction");

                    b.ToTable("Firefighter_Action");

                    b.HasData(
                        new
                        {
                            IdFirefighter = 1,
                            IdAction = 3
                        },
                        new
                        {
                            IdFirefighter = 2,
                            IdAction = 2
                        },
                        new
                        {
                            IdFirefighter = 3,
                            IdAction = 1
                        });
                });

            modelBuilder.Entity("Kolokwium.Models.FireTruck_Action", b =>
                {
                    b.HasOne("Kolokwium.Models.Action", "Action")
                        .WithMany("FireTruck_Actions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.FireTruck", "FireTruck")
                        .WithMany("FireTruck_Actions")
                        .HasForeignKey("IdFireTruck")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kolokwium.Models.Firefighter_Action", b =>
                {
                    b.HasOne("Kolokwium.Models.Action", "Action")
                        .WithMany("Firefighter_Actions")
                        .HasForeignKey("IdAction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kolokwium.Models.Firefighter", "Firefighter")
                        .WithMany("Firefighter_Actions")
                        .HasForeignKey("IdFirefighter")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
